/* tslint:disable */
/* eslint-disable */
/**
 * GOOVE
 * GOOVI API Design Spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateCompress,
    CreateCompressFromJSON,
    CreateCompressToJSON,
    TranscodeQueue,
    TranscodeQueueFromJSON,
    TranscodeQueueToJSON,
} from '../models';

export interface CompressPostRequest {
    createCompress?: CreateCompress;
}

export interface TranscodeGetRequest {
    id?: string;
}

/**
 * 
 */
export class TranscodeApi extends runtime.BaseAPI {

    /**
     * Create Compress
     */
    async compressPostRaw(requestParameters: CompressPostRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = this.configuration.apiKey("X-API-KEY"); // ApiKey authentication
        }

        const response = await this.request({
            path: `/compress`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCompressToJSON(requestParameters.createCompress),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create Compress
     */
    async compressPost(requestParameters: CompressPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<void> {
        await this.compressPostRaw(requestParameters, initOverrides);
    }

    /**
     * Get a transcode
     */
    async transcodeGetRaw(requestParameters: TranscodeGetRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<TranscodeQueue>> {
        const queryParameters: any = {};

        if (requestParameters.id !== undefined) {
            queryParameters['id'] = requestParameters.id;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = this.configuration.apiKey("X-API-KEY"); // ApiKey authentication
        }

        const response = await this.request({
            path: `/transcode`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TranscodeQueueFromJSON(jsonValue));
    }

    /**
     * Get a transcode
     */
    async transcodeGet(requestParameters: TranscodeGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<TranscodeQueue> {
        const response = await this.transcodeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
