/* tslint:disable */
/* eslint-disable */
/**
 * GOOVE
 * GOOVI API Design Spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    TranscodeQueue,
    TranscodeQueueFromJSON,
    TranscodeQueueToJSON,
} from '../models';

export interface TranscodeGetRequest {
    id?: string;
}

/**
 * 
 */
export class TranscodeApi extends runtime.BaseAPI {

    /**
     * Get a transcode
     */
    async transcodeGetRaw(requestParameters: TranscodeGetRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<TranscodeQueue>> {
        const queryParameters: any = {};

        if (requestParameters.id !== undefined) {
            queryParameters['id'] = requestParameters.id;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-KEY"] = this.configuration.apiKey("X-API-KEY"); // ApiKey authentication
        }

        const response = await this.request({
            path: `/transcode`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TranscodeQueueFromJSON(jsonValue));
    }

    /**
     * Get a transcode
     */
    async transcodeGet(requestParameters: TranscodeGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<TranscodeQueue> {
        const response = await this.transcodeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
