/* tslint:disable */
/* eslint-disable */
/**
 * Goovi ID
 * GOOVI ID Website spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Keys,
    KeysFromJSON,
    KeysToJSON,
    TranscodeQueue,
    TranscodeQueueFromJSON,
    TranscodeQueueToJSON,
} from '../models';

export interface TranscodeGetRequest {
    id?: string;
}

/**
 * 
 */
export class TranscodeApi extends runtime.BaseAPI {

    /**
     * Get a transcode
     */
    async transcodeGetRaw(requestParameters: TranscodeGetRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<Keys>> {
        const queryParameters: any = {};

        if (requestParameters.id !== undefined) {
            queryParameters['id'] = requestParameters.id;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Refresh authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Token authentication
        }

        const response = await this.request({
            path: `/transcode`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KeysFromJSON(jsonValue));
    }

    /**
     * Get a transcode
     */
    async transcodeGet(requestParameters: TranscodeGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<Keys> {
        const response = await this.transcodeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get list transcode
     */
    async transcodesGetRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<Array<TranscodeQueue>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Refresh authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["token"] = this.configuration.apiKey("token"); // Token authentication
        }

        const response = await this.request({
            path: `/transcodes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TranscodeQueueFromJSON));
    }

    /**
     * Get list transcode
     */
    async transcodesGet(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<Array<TranscodeQueue>> {
        const response = await this.transcodesGetRaw(initOverrides);
        return await response.value();
    }

}
