/*
GOOVE

GOOVI API Design Spec

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// TranscodeQueue struct for TranscodeQueue
type TranscodeQueue struct {
	QueueId *string `json:"queue_id,omitempty"`
	MerchantGivenId *string `json:"merchant_given_id,omitempty"`
	QueueStatus *string `json:"queue_status,omitempty"`
	ChargeStatus *string `json:"charge_status,omitempty"`
	TotalPrice *float32 `json:"total_price,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	ResolutionTarget []string `json:"resolution_target,omitempty"`
	FileTarget []string `json:"file_target,omitempty"`
	RequestDuration *int32 `json:"request_duration,omitempty"`
	Source *SourceTranscode `json:"source,omitempty"`
	Destination *SourceTranscode `json:"destination,omitempty"`
	BillingDetail []BillingDetail `json:"billing_detail,omitempty"`
	Media *MediaInfo `json:"media,omitempty"`
	TranscodeMeta NullableTranscodeMeta `json:"transcode_meta,omitempty"`
	Error NullableTranscodeError `json:"error,omitempty"`
}

// NewTranscodeQueue instantiates a new TranscodeQueue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTranscodeQueue() *TranscodeQueue {
	this := TranscodeQueue{}
	return &this
}

// NewTranscodeQueueWithDefaults instantiates a new TranscodeQueue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTranscodeQueueWithDefaults() *TranscodeQueue {
	this := TranscodeQueue{}
	return &this
}

// GetQueueId returns the QueueId field value if set, zero value otherwise.
func (o *TranscodeQueue) GetQueueId() string {
	if o == nil || o.QueueId == nil {
		var ret string
		return ret
	}
	return *o.QueueId
}

// GetQueueIdOk returns a tuple with the QueueId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranscodeQueue) GetQueueIdOk() (*string, bool) {
	if o == nil || o.QueueId == nil {
		return nil, false
	}
	return o.QueueId, true
}

// HasQueueId returns a boolean if a field has been set.
func (o *TranscodeQueue) HasQueueId() bool {
	if o != nil && o.QueueId != nil {
		return true
	}

	return false
}

// SetQueueId gets a reference to the given string and assigns it to the QueueId field.
func (o *TranscodeQueue) SetQueueId(v string) {
	o.QueueId = &v
}

// GetMerchantGivenId returns the MerchantGivenId field value if set, zero value otherwise.
func (o *TranscodeQueue) GetMerchantGivenId() string {
	if o == nil || o.MerchantGivenId == nil {
		var ret string
		return ret
	}
	return *o.MerchantGivenId
}

// GetMerchantGivenIdOk returns a tuple with the MerchantGivenId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranscodeQueue) GetMerchantGivenIdOk() (*string, bool) {
	if o == nil || o.MerchantGivenId == nil {
		return nil, false
	}
	return o.MerchantGivenId, true
}

// HasMerchantGivenId returns a boolean if a field has been set.
func (o *TranscodeQueue) HasMerchantGivenId() bool {
	if o != nil && o.MerchantGivenId != nil {
		return true
	}

	return false
}

// SetMerchantGivenId gets a reference to the given string and assigns it to the MerchantGivenId field.
func (o *TranscodeQueue) SetMerchantGivenId(v string) {
	o.MerchantGivenId = &v
}

// GetQueueStatus returns the QueueStatus field value if set, zero value otherwise.
func (o *TranscodeQueue) GetQueueStatus() string {
	if o == nil || o.QueueStatus == nil {
		var ret string
		return ret
	}
	return *o.QueueStatus
}

// GetQueueStatusOk returns a tuple with the QueueStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranscodeQueue) GetQueueStatusOk() (*string, bool) {
	if o == nil || o.QueueStatus == nil {
		return nil, false
	}
	return o.QueueStatus, true
}

// HasQueueStatus returns a boolean if a field has been set.
func (o *TranscodeQueue) HasQueueStatus() bool {
	if o != nil && o.QueueStatus != nil {
		return true
	}

	return false
}

// SetQueueStatus gets a reference to the given string and assigns it to the QueueStatus field.
func (o *TranscodeQueue) SetQueueStatus(v string) {
	o.QueueStatus = &v
}

// GetChargeStatus returns the ChargeStatus field value if set, zero value otherwise.
func (o *TranscodeQueue) GetChargeStatus() string {
	if o == nil || o.ChargeStatus == nil {
		var ret string
		return ret
	}
	return *o.ChargeStatus
}

// GetChargeStatusOk returns a tuple with the ChargeStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranscodeQueue) GetChargeStatusOk() (*string, bool) {
	if o == nil || o.ChargeStatus == nil {
		return nil, false
	}
	return o.ChargeStatus, true
}

// HasChargeStatus returns a boolean if a field has been set.
func (o *TranscodeQueue) HasChargeStatus() bool {
	if o != nil && o.ChargeStatus != nil {
		return true
	}

	return false
}

// SetChargeStatus gets a reference to the given string and assigns it to the ChargeStatus field.
func (o *TranscodeQueue) SetChargeStatus(v string) {
	o.ChargeStatus = &v
}

// GetTotalPrice returns the TotalPrice field value if set, zero value otherwise.
func (o *TranscodeQueue) GetTotalPrice() float32 {
	if o == nil || o.TotalPrice == nil {
		var ret float32
		return ret
	}
	return *o.TotalPrice
}

// GetTotalPriceOk returns a tuple with the TotalPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranscodeQueue) GetTotalPriceOk() (*float32, bool) {
	if o == nil || o.TotalPrice == nil {
		return nil, false
	}
	return o.TotalPrice, true
}

// HasTotalPrice returns a boolean if a field has been set.
func (o *TranscodeQueue) HasTotalPrice() bool {
	if o != nil && o.TotalPrice != nil {
		return true
	}

	return false
}

// SetTotalPrice gets a reference to the given float32 and assigns it to the TotalPrice field.
func (o *TranscodeQueue) SetTotalPrice(v float32) {
	o.TotalPrice = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *TranscodeQueue) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranscodeQueue) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *TranscodeQueue) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *TranscodeQueue) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetResolutionTarget returns the ResolutionTarget field value if set, zero value otherwise.
func (o *TranscodeQueue) GetResolutionTarget() []string {
	if o == nil || o.ResolutionTarget == nil {
		var ret []string
		return ret
	}
	return o.ResolutionTarget
}

// GetResolutionTargetOk returns a tuple with the ResolutionTarget field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranscodeQueue) GetResolutionTargetOk() ([]string, bool) {
	if o == nil || o.ResolutionTarget == nil {
		return nil, false
	}
	return o.ResolutionTarget, true
}

// HasResolutionTarget returns a boolean if a field has been set.
func (o *TranscodeQueue) HasResolutionTarget() bool {
	if o != nil && o.ResolutionTarget != nil {
		return true
	}

	return false
}

// SetResolutionTarget gets a reference to the given []string and assigns it to the ResolutionTarget field.
func (o *TranscodeQueue) SetResolutionTarget(v []string) {
	o.ResolutionTarget = v
}

// GetFileTarget returns the FileTarget field value if set, zero value otherwise.
func (o *TranscodeQueue) GetFileTarget() []string {
	if o == nil || o.FileTarget == nil {
		var ret []string
		return ret
	}
	return o.FileTarget
}

// GetFileTargetOk returns a tuple with the FileTarget field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranscodeQueue) GetFileTargetOk() ([]string, bool) {
	if o == nil || o.FileTarget == nil {
		return nil, false
	}
	return o.FileTarget, true
}

// HasFileTarget returns a boolean if a field has been set.
func (o *TranscodeQueue) HasFileTarget() bool {
	if o != nil && o.FileTarget != nil {
		return true
	}

	return false
}

// SetFileTarget gets a reference to the given []string and assigns it to the FileTarget field.
func (o *TranscodeQueue) SetFileTarget(v []string) {
	o.FileTarget = v
}

// GetRequestDuration returns the RequestDuration field value if set, zero value otherwise.
func (o *TranscodeQueue) GetRequestDuration() int32 {
	if o == nil || o.RequestDuration == nil {
		var ret int32
		return ret
	}
	return *o.RequestDuration
}

// GetRequestDurationOk returns a tuple with the RequestDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranscodeQueue) GetRequestDurationOk() (*int32, bool) {
	if o == nil || o.RequestDuration == nil {
		return nil, false
	}
	return o.RequestDuration, true
}

// HasRequestDuration returns a boolean if a field has been set.
func (o *TranscodeQueue) HasRequestDuration() bool {
	if o != nil && o.RequestDuration != nil {
		return true
	}

	return false
}

// SetRequestDuration gets a reference to the given int32 and assigns it to the RequestDuration field.
func (o *TranscodeQueue) SetRequestDuration(v int32) {
	o.RequestDuration = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *TranscodeQueue) GetSource() SourceTranscode {
	if o == nil || o.Source == nil {
		var ret SourceTranscode
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranscodeQueue) GetSourceOk() (*SourceTranscode, bool) {
	if o == nil || o.Source == nil {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *TranscodeQueue) HasSource() bool {
	if o != nil && o.Source != nil {
		return true
	}

	return false
}

// SetSource gets a reference to the given SourceTranscode and assigns it to the Source field.
func (o *TranscodeQueue) SetSource(v SourceTranscode) {
	o.Source = &v
}

// GetDestination returns the Destination field value if set, zero value otherwise.
func (o *TranscodeQueue) GetDestination() SourceTranscode {
	if o == nil || o.Destination == nil {
		var ret SourceTranscode
		return ret
	}
	return *o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranscodeQueue) GetDestinationOk() (*SourceTranscode, bool) {
	if o == nil || o.Destination == nil {
		return nil, false
	}
	return o.Destination, true
}

// HasDestination returns a boolean if a field has been set.
func (o *TranscodeQueue) HasDestination() bool {
	if o != nil && o.Destination != nil {
		return true
	}

	return false
}

// SetDestination gets a reference to the given SourceTranscode and assigns it to the Destination field.
func (o *TranscodeQueue) SetDestination(v SourceTranscode) {
	o.Destination = &v
}

// GetBillingDetail returns the BillingDetail field value if set, zero value otherwise.
func (o *TranscodeQueue) GetBillingDetail() []BillingDetail {
	if o == nil || o.BillingDetail == nil {
		var ret []BillingDetail
		return ret
	}
	return o.BillingDetail
}

// GetBillingDetailOk returns a tuple with the BillingDetail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranscodeQueue) GetBillingDetailOk() ([]BillingDetail, bool) {
	if o == nil || o.BillingDetail == nil {
		return nil, false
	}
	return o.BillingDetail, true
}

// HasBillingDetail returns a boolean if a field has been set.
func (o *TranscodeQueue) HasBillingDetail() bool {
	if o != nil && o.BillingDetail != nil {
		return true
	}

	return false
}

// SetBillingDetail gets a reference to the given []BillingDetail and assigns it to the BillingDetail field.
func (o *TranscodeQueue) SetBillingDetail(v []BillingDetail) {
	o.BillingDetail = v
}

// GetMedia returns the Media field value if set, zero value otherwise.
func (o *TranscodeQueue) GetMedia() MediaInfo {
	if o == nil || o.Media == nil {
		var ret MediaInfo
		return ret
	}
	return *o.Media
}

// GetMediaOk returns a tuple with the Media field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TranscodeQueue) GetMediaOk() (*MediaInfo, bool) {
	if o == nil || o.Media == nil {
		return nil, false
	}
	return o.Media, true
}

// HasMedia returns a boolean if a field has been set.
func (o *TranscodeQueue) HasMedia() bool {
	if o != nil && o.Media != nil {
		return true
	}

	return false
}

// SetMedia gets a reference to the given MediaInfo and assigns it to the Media field.
func (o *TranscodeQueue) SetMedia(v MediaInfo) {
	o.Media = &v
}

// GetTranscodeMeta returns the TranscodeMeta field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TranscodeQueue) GetTranscodeMeta() TranscodeMeta {
	if o == nil || o.TranscodeMeta.Get() == nil {
		var ret TranscodeMeta
		return ret
	}
	return *o.TranscodeMeta.Get()
}

// GetTranscodeMetaOk returns a tuple with the TranscodeMeta field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TranscodeQueue) GetTranscodeMetaOk() (*TranscodeMeta, bool) {
	if o == nil {
		return nil, false
	}
	return o.TranscodeMeta.Get(), o.TranscodeMeta.IsSet()
}

// HasTranscodeMeta returns a boolean if a field has been set.
func (o *TranscodeQueue) HasTranscodeMeta() bool {
	if o != nil && o.TranscodeMeta.IsSet() {
		return true
	}

	return false
}

// SetTranscodeMeta gets a reference to the given NullableTranscodeMeta and assigns it to the TranscodeMeta field.
func (o *TranscodeQueue) SetTranscodeMeta(v TranscodeMeta) {
	o.TranscodeMeta.Set(&v)
}
// SetTranscodeMetaNil sets the value for TranscodeMeta to be an explicit nil
func (o *TranscodeQueue) SetTranscodeMetaNil() {
	o.TranscodeMeta.Set(nil)
}

// UnsetTranscodeMeta ensures that no value is present for TranscodeMeta, not even an explicit nil
func (o *TranscodeQueue) UnsetTranscodeMeta() {
	o.TranscodeMeta.Unset()
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TranscodeQueue) GetError() TranscodeError {
	if o == nil || o.Error.Get() == nil {
		var ret TranscodeError
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TranscodeQueue) GetErrorOk() (*TranscodeError, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *TranscodeQueue) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableTranscodeError and assigns it to the Error field.
func (o *TranscodeQueue) SetError(v TranscodeError) {
	o.Error.Set(&v)
}
// SetErrorNil sets the value for Error to be an explicit nil
func (o *TranscodeQueue) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *TranscodeQueue) UnsetError() {
	o.Error.Unset()
}

func (o TranscodeQueue) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.QueueId != nil {
		toSerialize["queue_id"] = o.QueueId
	}
	if o.MerchantGivenId != nil {
		toSerialize["merchant_given_id"] = o.MerchantGivenId
	}
	if o.QueueStatus != nil {
		toSerialize["queue_status"] = o.QueueStatus
	}
	if o.ChargeStatus != nil {
		toSerialize["charge_status"] = o.ChargeStatus
	}
	if o.TotalPrice != nil {
		toSerialize["total_price"] = o.TotalPrice
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.ResolutionTarget != nil {
		toSerialize["resolution_target"] = o.ResolutionTarget
	}
	if o.FileTarget != nil {
		toSerialize["file_target"] = o.FileTarget
	}
	if o.RequestDuration != nil {
		toSerialize["request_duration"] = o.RequestDuration
	}
	if o.Source != nil {
		toSerialize["source"] = o.Source
	}
	if o.Destination != nil {
		toSerialize["destination"] = o.Destination
	}
	if o.BillingDetail != nil {
		toSerialize["billing_detail"] = o.BillingDetail
	}
	if o.Media != nil {
		toSerialize["media"] = o.Media
	}
	if o.TranscodeMeta.IsSet() {
		toSerialize["transcode_meta"] = o.TranscodeMeta.Get()
	}
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableTranscodeQueue struct {
	value *TranscodeQueue
	isSet bool
}

func (v NullableTranscodeQueue) Get() *TranscodeQueue {
	return v.value
}

func (v *NullableTranscodeQueue) Set(val *TranscodeQueue) {
	v.value = val
	v.isSet = true
}

func (v NullableTranscodeQueue) IsSet() bool {
	return v.isSet
}

func (v *NullableTranscodeQueue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTranscodeQueue(val *TranscodeQueue) *NullableTranscodeQueue {
	return &NullableTranscodeQueue{value: val, isSet: true}
}

func (v NullableTranscodeQueue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTranscodeQueue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


