/* tslint:disable */
/* eslint-disable */
/**
 * Goovi ID
 * GOOVI ID Website spec
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SourceTranscode,
    SourceTranscodeFromJSON,
    SourceTranscodeFromJSONTyped,
    SourceTranscodeToJSON,
} from './SourceTranscode';

/**
 * 
 * @export
 * @interface CreateCompress
 */
export interface CreateCompress {
    /**
     * 
     * @type {string}
     * @memberof CreateCompress
     */
    merchantGivenId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCompress
     */
    callbackUrl?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateCompress
     */
    sizes?: Array<number>;
    /**
     * 
     * @type {SourceTranscode}
     * @memberof CreateCompress
     */
    source?: SourceTranscode;
    /**
     * 
     * @type {SourceTranscode}
     * @memberof CreateCompress
     */
    destination?: SourceTranscode;
}

export function CreateCompressFromJSON(json: any): CreateCompress {
    return CreateCompressFromJSONTyped(json, false);
}

export function CreateCompressFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCompress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'merchantGivenId': !exists(json, 'merchant_given_id') ? undefined : json['merchant_given_id'],
        'callbackUrl': !exists(json, 'callback_url') ? undefined : json['callback_url'],
        'sizes': !exists(json, 'sizes') ? undefined : json['sizes'],
        'source': !exists(json, 'source') ? undefined : SourceTranscodeFromJSON(json['source']),
        'destination': !exists(json, 'destination') ? undefined : SourceTranscodeFromJSON(json['destination']),
    };
}

export function CreateCompressToJSON(value?: CreateCompress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'merchant_given_id': value.merchantGivenId,
        'callback_url': value.callbackUrl,
        'sizes': value.sizes,
        'source': SourceTranscodeToJSON(value.source),
        'destination': SourceTranscodeToJSON(value.destination),
    };
}

